version: '3.7'
services:

  aerospike-tester:
    build: 
      context: .
      dockerfile: Dockerfile.aerospike


  aerospike:
    image: aerospike/aerospike-server:latest
    ports:
      - '3000:3000'